CREATE SCHEMA Address
GO

GO


CREATE TABLE Address.Person
(
	familyName NATIONAL CHARACTER VARYING(20) NOT NULL,
	givenNames NATIONAL CHARACTER VARYING(20) NOT NULL,
	firstStreetLine NATIONAL CHARACTER VARYING(64) NOT NULL,
	secondStreetLine NATIONAL CHARACTER VARYING(64) NOT NULL,
	thirdStreetLine NATIONAL CHARACTER VARYING(64) NOT NULL,
	city NATIONAL CHARACTER VARYING(64) NOT NULL,
	postcode NATIONAL CHARACTER VARYING(MAX) NOT NULL,
	streetNumber NATIONAL CHARACTER VARYING(12) NOT NULL,
	CONSTRAINT PersonIsKnownByFamilyNameGivenName PRIMARY KEY(familyName, givenNames)
)
GO


CREATE TABLE Address.Company
(
	companyName NATIONAL CHARACTER VARYING(MAX) NOT NULL,
	firstStreetLine NATIONAL CHARACTER VARYING(64) NOT NULL,
	secondStreetLine NATIONAL CHARACTER VARYING(64) NOT NULL,
	thirdStreetLine NATIONAL CHARACTER VARYING(64) NOT NULL,
	city NATIONAL CHARACTER VARYING(64) NOT NULL,
	postcode NATIONAL CHARACTER VARYING(MAX) NOT NULL,
	streetNumber NATIONAL CHARACTER VARYING(12) NOT NULL,
	CONSTRAINT InternalUniquenessConstraint2 PRIMARY KEY(companyName)
)
GO


GO