CREATE SCHEMA SimpleMandatory
GO

GO

CREATE TABLE SimpleMandatory.Person
(
	FamilyName NATIONAL CHARACTER VARYING(20) NOT NULL, 
	GivenName NATIONAL CHARACTER VARYING(20) NOT NULL, 
	Address_Street_StreetLine1 NATIONAL CHARACTER VARYING(64) , 
	Address_Street_StreetLine2 NATIONAL CHARACTER VARYING(64) , 
	Address_City NATIONAL CHARACTER VARYING() , 
	Address_Postcode NATIONAL CHARACTER VARYING() , 
	Address_StreetNumber NATIONAL CHARACTER VARYING(10) , 
	CONSTRAINT PrsnIsKnwnByFmlyNmGvnNm PRIMARY KEY(FamilyName, GivenName)
)
GO



GO