vocabulary Units;

// primitive units:
// m kg sec coul candela dollar bit erlang K

// prefixes
1e24 converts to yotta;
1e21 converts to zetta;
1e18 converts to exa;
1e15 converts to peta;
1e12 converts to tera;
1e9 converts to giga;
1e6 converts to mega;
1e4 converts to myria;
1e3 converts to kilo;
1e2 converts to hecto;
1e1 converts to deka;
1e-1 converts to deci;
1e-2 converts to centi;
1e-3 converts to milli;
1e-6 converts to micro;
1e-9 converts to nano;
1e-12 converts to pico;
1e-15 converts to femto;
1e-18 converts to atto;
1e-21 converts to zopto;
1e-24 converts to yocto;
0.5 converts to semi;
0.5 converts to demi;

1 yotta converts to Y;
1 zetta converts to Z;
1 exa converts to E;
1 peta converts to P;
1 tera converts to T;
1 giga converts to G;
1 mega converts to M;
1 kilo converts to k;
1 hecto converts to h;
1 deka converts to da;
1 deci converts to d;
1 centi converts to c;
1 milli converts to m;
1 nano converts to n;
1 pico converts to p;
1 femto converts to f;
1 atto converts to a;
1 zopto converts to z;
1 yocto converts to y;

// binary prefixes introduced in 1999
1152921504606846976 converts to exbi;
1125899906842624 converts to pebi;
1099511627776 converts to tebi;
1073741824 converts to gibi;
1048576 converts to mebi;
1024 converts to kibi;
1 exbi converts to Ei;
1 pebi converts to Pi;
1 tebi converts to Ti;
1 gibi converts to Gi;
1 mebi converts to Mi;
1 kibi converts to Ki;

// Dimensionless Constants
13 converts to bakersdozen;
1/24 converts to caratgold;
12 converts to dozen;
144 converts to gross;
1/24 converts to karat;
6.022169e+23 converts to mole approximately;
3.14159265358979 converts to pi;
1/200 converts to proof;
25 converts to quire;
500 converts to ream;
0.5 pi converts to radian;
1/180 pi radian converts to degree;
2 pi radian converts to circle;
1 circle converts to turn;
1 turn converts to revolution;
1 turn converts to rev;
0.9 degree converts to grade;

// Dimensional constants
9.80665 m sec^-2 converts to g;					// Average gravitational pull at sea level
6.6739e-11 m^3 kg^-1 sec^-2 converts to bigG;			// The gravtational constant
299792458.0 m sec^-1 converts to lightspeed approximately;	// Speed of light
149597871000.0 m converts to au approximately;			// Astronomical unit
1.6021917e-19 coul converts to e approximately;			// Charge on an electron
1 lightspeed^2 converts to energy;				// Thanks Einstein!
133322.0 kg m^-2 sec^-2 converts to mercury;			// Atmospheric pressure
1.0e-15 m converts to fermi;
1 g converts to force;
1 mercury converts to hg;
1 degree converts to arcdeg;
1/60 arcdeg converts to arcmin;
1/60 arcmin converts to arcsec;
1/36 erlang converts to ccs;
1 radian^2 converts to steradian;
4 pi steradian converts to sphere;
1 steradian converts to sr;

// Time
1 sec converts to second;
1 sec converts to s;
60 sec converts to minute;
1 minute converts to min;
60 min converts to hour;
1 hour converts to hr;
24 hr converts to day;
7 day converts to week;
14 day converts to fortnight;
365.24219879 day converts to year approximately;
1 year converts to yr;
1/12 year converts to month;
1 month converts to mo;
1.0e-06 sec converts to us;
10 yr converts to decade;
100 year converts to century;
1000 year converts to millennium;
1 rev minute^-1 converts to rpm;
1 rev sec^-1 converts to rps;

// Mass
0.001 kg converts to gram;
1 gram converts to gm;
1 gram converts to gramme;
100 kg converts to quintal;
1000.0 kg converts to metricton;
1000000.0 gm converts to tonne;

// Avoirdupois and Apothecary
0.45359237 kg converts to lb;
1 lb converts to pound;
1 lb g converts to lbf;
1/16 lb converts to ounce;
1 ounce converts to oz;
1/16 oz converts to dram;
1 dram converts to dr;
1/7000 lb converts to grain;
60 grain converts to drachm;
1 grain converts to gr;
2000 lb converts to shortton;
1 shortton converts to ton;
2240 lb converts to longton;
14 lb converts to stone;
100 lb converts to shorthundredweight;
25 lb converts to shortquarter;
112 lb converts to longhundredweight;
28 lb converts to longquarter;
252 lb converts to weymass;
94 lb converts to bag;
100 lb converts to cental;
20 grain converts to scruple;
60 grain converts to apdram;
480 grain converts to apounce;
5760 grain converts to appound;
1 appound converts to troypound;

// Length, Area and Volume
1 m converts to meter;
1 meter converts to metre;
0.001 m converts to mm;
1.0e-06 meter converts to micron;
1.0e-10 meter converts to angstrom;
0.01 m^3 converts to cc;
1000.0 cc converts to liter;
1 liter converts to litre;
0.001 liter converts to ml;
100.0 m^2 converts to are;
10000.0 m^2 converts to hectare;
0.0003 m^3 converts to drop;

25.4 mm converts to inch/inches;
1 inch converts to in;
12 in converts to foot/feet;
1 foot converts to ft;
3 ft converts to yard;
1 yard converts to yd;
5.5 yd converts to rod;
1 rod converts to rd;
1 rd converts to perch;
1 rd converts to pole;
5280 ft converts to mile;
1 mile converts to mi;
100 ft^2 converts to square;
1210.0 yd converts to rood;
33/50 ft converts to link;
4840 yd^2 converts to acre;
0.001 in converts to mil;
0.01 in converts to caliber;
1/40 in converts to bottommeasure;
1/12 in converts to line;
1/3 in converts to barleycorn;
3 in converts to palm;
4 in converts to hand;
9 in converts to quarter;
9 in converts to span;
18 in converts to cubit;
45 in converts to ell;
7/8 in converts to finger;
1.5 ft^3 min^-1 converts to minersinch;
16/15 ft converts to frenchfoot;
1 frenchfoot converts to frenchfeet;
6 frenchfeet converts to toise;
36 in converts to pace;
2.5 feet converts to militarypace;
1 ft converts to engineerslink;
100 ft converts to engineerschain;

331.46 m sec^-1 converts to mach;
1 mile hr^-1 converts to mph;

// Nautical
3 mi converts to league;
1852 m converts to nmile;
3 nmile converts to marineleague;
1 nmile converts to nauticalmile;
6 ft converts to fathom;
1 nmile hr^-1 converts to knot;
6080 ft hr^-1 converts to admiraltyknot;
100 ft^3 converts to registerton;
40 ft^3 converts to shippington;
35 ft^3 converts to displacementton;

// US Liquid
231 in^3 converts to gallon;
1.20095 converts to imperial;
1 gallon converts to gal;
1/4 gal converts to quart;
1 quart converts to qt;
1/2 qt converts to pint;
1 pint converts to pt;
1/16 pt converts to floz;
1/8 floz converts to fldr;
3/2 floz converts to shot;

// US dry measures
268.8025 in^3 gallon^-1 converts to dry approximately;
8 dry quart converts to peck;
1 peck converts to pk;
4 peck converts to bushel;
1 bushel converts to bu;
36 bushel converts to chaldron;
4 bu converts to coomb;
80 bu converts to last;
3 bu converts to sack;
8 bu converts to seam;
2 bu converts to strike;
40 bu converts to wey;

// British dry
277.42 in^3 converts to brgallon approximately;
1/4 brgallon converts to brquart;
1/2 brquart converts to brpint;
1/20 brpint converts to brfloz;
554.84 in^3 converts to brpeck approximately;
4 brpeck converts to brbushel;
37.5 brgallon converts to cran;

// Energy and Work
1 kg m sec^-2 converts to newton;
1 newton converts to nt;
1 newton converts to N;
1 nt m converts to joule;
4.1868 joule converts to cal;
1000000.0 cal converts to thermie;
550 ft lb g sec^-1 converts to horsepower;
1 horsepower converts to hp;
0.01 m gm sec^-2 converts to dyne;
0.01 m^2 gm sec^-2 converts to erg;
1 cal converts to calorie;
1055.06 joule converts to britishthermalunit approximately;
1 britishthermalunit converts to btu;
100000.0 btu converts to therm;
1000.0 cal converts to frigorie;

// Electrical
1 coul converts to coulomb;
1 coul converts to C;
3.336e-30 coul m converts to debye;
1 coul sec^-1 converts to ampere;
1 ampere converts to amp;
1 joule sec^-1 converts to watt;
1 watt amp^-1 converts to volt;
1 volt amp^-1 converts to ohm;
1 ohm^-1 converts to siemens;
1 ohm^-1 converts to mho;
1 coul volt^-1 converts to farad;
1 sec^2 farad^-1 converts to henry;
0.001 henry converts to mh;
1 volt sec converts to weber;
1 weber m^-2 converts to tesla;
1 volt converts to V;
1000.0 ohm converts to kilohm;
1000000.0 ohm converts to megohm;
0.0001 weber m^-2 converts to gauss;
1.0e-08 weber converts to maxwell;
1.0e-12 farad converts to pf;
3.33564095198152e-10 coul converts to statcoul;
1 statcoul converts to statcoulomb;
96520.0 coul converts to faraday;
3.33564e-10 coul converts to franklin;
10 amp converts to biot;
0.795775 amp converts to gilbert;
250.0 pi amp m^-1 converts to oersted;
1 oersted converts to oe;
3.33564095198152e-10 amp converts to statamp;
1 statamp converts to statampere;
299.792458 volt converts to statvolt;

// Frequency
1 sec^-1 converts to hertz;
1 hertz converts to Hz;
1 sec^-1 converts to hz;
1000.0 sec^-1 converts to khz;
1000000.0 sec^-1 converts to mhz;
1000000.0 sec^-1 converts to rutherford;
1000000000000.0 hertz converts to fresnel;

// Light
1 candela converts to cd;
1.02 candela converts to candle;
1 cd sr converts to lumen;
1 cd sr m^-2 converts to lux;
1 lumen ft^-2 converts to footcandle;
1 cd pi^-1 ft^-2 converts to footlambert;
1 cd m^-2 converts to nit;
0.92 cd converts to hefnercandle;
100.0 cd m^-2 converts to stilb;
1 cd pi^-1 m^-2 converts to apostilb;
1 cd pi^-1 m^-2 converts to blondel;
100.0 cd pi^-1 m^-2 converts to equivalentphot;
100.0 cd pi^-1 m^-2 converts to lambert;
1 lumen pi^-1 ft^-2 converts to equivalentfootcandle;
100.0 lumen m^-2 converts to phot;
1 lumen pi^-1 m^-2 converts to equivalentlux;
0.001 lux converts to nox;

// Computer terms
1 bit sec^-1 converts to baud;
8 bit converts to byte;
512 byte converts to block;
1024 byte converts to kbyte;
1024 kbyte converts to megabyte;
1024 megabyte converts to gigabyte;
1 megabyte converts to meg;

// Temperature
1 K + 273.15 converts to degC;
5/9 degC + 32 converts to degF;
1 K converts to kelvin;
5/4 degC converts to degreaumur;
1 degF converts to degreerankine;
1 degF converts to degreesrankine;
1 degreesrankine converts to degrankine;

// Astronomical
23.934469444 hour converts to siderealday;
1/24 siderealday converts to siderealhour;
27.32152777 day converts to siderealmonth;
365.256360417 day converts to siderealyear;
29.5305555 day converts to lunarmonth;
12 lunarmonth converts to lunaryear;
1 lunarmonth converts to synodicmonth;
1 lightspeed yr converts to lightyear;
1 year converts to solaryear;
1 year converts to tropicalyear;
5.97223e+24 kg converts to m_earth;
7.34e+22 kg converts to m_moon;
1.98843e+30 kg converts to m_sun;
1 au radian arcsec^-1 converts to parsec;
1 parsec converts to pc;
1 au converts to astronomicalunit;

// Atomic
1.6606e-27 kg converts to neutronmass;
1.6726e-27 kg converts to protonmass;
9.1095e-31 kg converts to electronmass;
1.055e-34 joule sec converts to hbar;
1.1125945705385e-10 hbar^2 C^2 N^-1 m^-2 e^-2 electronmass^-1 converts to bohrradius;
1.66044e-27 kg converts to atomicmassunit approximately;
1 atomicmassunit converts to amu;
1 amu converts to dalton;
6.626e-34 joule sec converts to planck;				// The Planck constant
1000000000.0 e volt converts to bev;
1 e V converts to eV;
1 e volt converts to electronvolt;
1 e volt converts to ev;

// British and surveying
220 yd converts to furlong;
22 yd converts to gunterschain;
1200/3937 m ft^-1 converts to british;
66 ft converts to chain;
1 british ft converts to geodeticfoot;
1 british ft converts to surveyfoot;
3 surveyfoot converts to surveyyard;
66 ft converts to surveyorschain;
33/50 ft converts to surveyorslink;
720 ft converts to cable;
40 yd converts to bolt;
20 ft converts to rope;
1852 m converts to geographicalmile;

// Pressure
101325.0 nt m^-2 converts to atmosphere;
100000.0 nt m^-2 converts to bar;
1 lb g in^-2 converts to psi;
1 atmosphere converts to atm;
0.001 m hg converts to torr;
0.1 nt m^-2 converts to barie;
0.1 nt m^-2 converts to barye;
1 nt m^-2 converts to pascal;
1000.0 nt m^-2 converts to pieze;

// Printers
1/6 in converts to pica;
1/72 in converts to point;

// Alcohol and wine
1/8 qt converts to noggin;
1/4 pt converts to gill;
4/5 qt converts to fifth;
42 gal converts to barrel;
2 barrel converts to hogshead;
4/5 gal converts to jeroboam;
1 hogshead converts to hd;
4 barrel converts to pipe;
8 barrel converts to tun;
9 gal converts to firkin;
2 qt converts to magnum;
18 gal converts to kilderkin;
156 floz converts to rehoboam;

// Cooking measures
1/60 fldr converts to minim;
4 fldr converts to tablespoon;
1 tablespoon converts to tbl;
1 tablespoon converts to tbsp;
4/3 fldr converts to teaspoon;
1 teaspoon converts to tsp;
1/2 pt converts to cup;

// Radiation
37000000000.0 sec^-1 converts to curie;
2.7027027027027e-11 curie converts to becquerel;
0.000258 curie kg^-1 converts to rontgen;
8.4 rontgen converts to sievert;

// Flow rate and consumption
1 ft^3 sec^-1 converts to cfs;
1000000.0 gal day^-1 converts to mgd;
1 mile gal^-1 converts to mpg;

// Lumber
144 in^3 converts to boardfoot;
128 ft^3 converts to cord;
1 cord converts to cordfoot;
1 ft^3 converts to timberfoot;

// Thread
900 ft pound^-1 converts to linenyarncount;
1 meter gram^-1 converts to metricyarncount;
0.000111111111111111 gram m converts to denier;
1680 ft pound^-1 converts to worstedyarncount;
2520 ft pound^-1 converts to cottonyarncount;
120 yd converts to skein;
14400 yd converts to spindle;

// Jewelers
0.205 g converts to carat;
1/20 oz converts to pennyweight;
1 pennyweight converts to pwt;
0.2 g converts to metriccarat;
0.002 gram converts to jewlerspoint;

// Trivia
1.0e-06 sec converts to sigma;
1 m^3 converts to stere;
0.0001 m^2 sec^-1 converts to stoke;
4600000.0 m^2 sec^-2 converts to tnt;
1.00202e-13 m converts to Xunit;
1.0e-28 m^2 converts to barn;
1 m^-1 converts to dipotre;
100 kg converts to doppelzentner;
0.01 m sec^-2 converts to galileo;
6.28e-05 gram converts to iudiptheria;
4.167e-05 gram converts to iuinsulin;
6.0e-07 gram converts to iupenicillin;
1 kg converts to key;
100 kg m g sec converts to poncelet;
2 pi sec^-1 converts to pulsatance;
10 m^2 nt^-1 sec^-1 converts to rhe;
0.001 apostilb converts to skot;
1000.0 nt converts to sthene;
0.001 gram m converts to tex;
1 gram g cc converts to water;
1.0e-12 m^2 newton^-1 converts to brewster;
0.01 grade converts to centesimalminute;
0.0001 grade converts to centesimalsecond;
37.2 inch converts to scottishell;
45 inch converts to englishell;
27 inch converts to flemishell;
1 gm force sec^2 m^-1 converts to hyl;
1000 lbf converts to kip;
1.0e-09 m hg m^3 s^-1 converts to lusec;
100.0 gm m^-1 sec^-1 converts to poise;
4 pi sr converts to spat;
1/4 pi in^2 converts to circularinch;
2.5e-07 pi in^2 converts to circularmil;
1.0e-11 m hg m^3 s^-1 converts to clusec;
0.0906 gm converts to crith;
// 1.38047e-16 erg degC^-1 converts to k;
100.0 cal m^-2 converts to langley;
1 ft lb sec^-2 converts to poundal;
100 erg gm^-1 converts to rad;
12000 btu ton^-1 hour^-1 converts to refrigeration;
1 ft^2 converts to sabin;
1 lb g sec^2 ft^-1 converts to slug;
191.835 ft converts to arpentlin;
1.0e-09 weber m^-2 converts to gamma;
1/16 yd converts to nail;
3.5 mi converts to parasang;
1 poundal converts to pdl;
13.6054 ev converts to rydberg;
27.52 mi converts to arpentcan;
1/4 mi^2 converts to homestead;
1/4 mi^2 converts to quartersection;
1 mi^2 converts to section;
36 mi^2 converts to township;

/*
 * REVISIT: These currency conversions haven't been updated since 1993
 *
5 dollar converts to fin ephemeral;
1 dollar converts to argentinapeso ephemeral;
0.66 dollar converts to australiadollar ephemeral;
2.6522 dollar converts to bahraindinar ephemeral;
1.9e-05 dollar converts to brazilcruzeiro ephemeral;
1.49 dollar converts to britainpound ephemeral;
1 britainpound converts to greatbritainpound;
1 dollar converts to buck ephemeral;
0.77 dollar converts to canadadollar ephemeral;
0.01 dollar converts to cent ephemeral;
0.0025 dollar converts to chilepeso ephemeral;
0.174856 dollar converts to chinarenminbi ephemeral;
0.001495 dollar converts to colombiapeso ephemeral;
0.034 dollar converts to czechkoruna ephemeral;
0.15 dollar converts to denmarkkrone ephemeral;
0.000539 dollar converts to ecuadorsucre ephemeral;
0.0043 dollar converts to greecedrachma ephemeral;
0.13 dollar converts to hongkongdollar ephemeral;
0.011 dollar converts to hungaryforint ephemeral;
0.03211 dollar converts to indiarupee ephemeral;
0.0004782 dollar converts to indonesiarupiah ephemeral;
0.3642 dollar converts to israelshekel ephemeral;
0.0093 dollar converts to japanyen ephemeral;
1.4682 dollar converts to jordandinar ephemeral;
3.3173 dollar converts to kuwaitdinar ephemeral;
0.000578 dollar converts to lebanonpound ephemeral;
0.338 dollar converts to malaysiaringgit ephemeral;
2.6042 dollar converts to maltalira ephemeral;
0.3205128 dollar converts to mexicopeso ephemeral;
0.539 dollar converts to newzealanddollar ephemeral;
0.139 dollar converts to norwaykrone ephemeral;
0.037 dollar converts to pakistanrupee ephemeral;
0.5065 dollar converts to perunewsol ephemeral;
0.03738 dollar converts to philippinespeso ephemeral;
5.9e-05 dollar converts to polandzloty ephemeral;
0.26702 dollar converts to saudiarabiariyal ephemeral;
0.6157 dollar converts to singaporedollar ephemeral;
0.034 dollar converts to slovakkoruna ephemeral;
0.21 dollar converts to southafricarand ephemeral;
0.001 dollar converts to southkoreawon ephemeral;
0.13 dollar converts to swedenkrona ephemeral;
0.66 dollar converts to switzerlandfranc ephemeral;
0.038285 dollar converts to taiwandollar ephemeral;
0.03962 dollar converts to thailandbaht ephemeral;
9.29e-05 dollar converts to turkeylira ephemeral;
0.2723 dollar converts to unitedarabdirham ephemeral;
0.246852 dollar converts to uruguaynewpeso ephemeral;
0.011 dollar converts to venezuelabolivar ephemeral;
*/
